apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: ulminator/sentiment-analysis-frontend 
      name: sa-frontend
      ports:
        - containerPort: 80